=== pgarman524/lenguaje-de-marcas-T4/act02/Concesionario.dtd
<!ELEMENT Concesionario (concesionario*)>
<!ELEMENT concesionario (cod_coche, marca, modelo, matricula, potencia, plazas, num_puertas)>
<!ELEMENT cod_coche (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT num_puertas (#PCDATA)>

=== pgarman524/lenguaje-de-marcas-T4/act03/Concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Concesionario SYSTEM "../act02/Concesionario.dtd">

<Concesionario>
    <concesionario>
        <cod_coche>2511600956</cod_coche>
        <marca>CITROEN</marca>
        <modelo>C3 Aircross PureTech</modelo>
        <matricula>567489120</matricula>
        <potencia>110CV</potencia>
        <plazas>5</plazas>
        <num_puertas>4</num_puertas>
    </concesionario>

</Concesionario>
