=== pgarman524/lenguaje-de-marcas-T4/act02/Mueble.dtd
<!ELEMENT Mueble (mueble*)>
<!ELEMENT mueble (cod_mueble, tipo, modelo, num_almacen, dificultad_ensamblaje, materiales, lugar_uso)>
<!ELEMENT cod_mueble (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT num_almacen (#PCDATA)>
<!ELEMENT dificultad_ensamblaje (#PCDATA)>
<!ELEMENT materiales (#PCDATA)>
<!ELEMENT lugar_uso (#PCDATA)>

=== pgarman524/lenguaje-de-marcas-T4/act03/Mueble_D.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mueble SYSTEM "../act02/Mueble.dtd">

<Mueble>
    <mueble>
        <cod_mueble>004.729.62</cod_mueble>
        <tipo>sofas</tipo>
        <modelo>BOLLSTANÃ„S</modelo>
        <num_almacen>5700</num_almacen>
        <dificultad_ensamblaje>easy</dificultad_ensamblaje>
        <materiales>poliester</materiales>
        <lugar_uso>salon</lugar_uso>

    </mueble>


</Mueble>
