=== pgarman524/lenguaje-de-marcas-T4/act05/alumnado.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:element name="Alumnado">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Estudiante" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="NIF" type="xs:string"/>
              <xs:element name="Resultado" type="xs:string"/>
              <xs:element name="Observaciones" type="xs:string" minOccurs="0"/>
              <xs:element name="IP" type="xs:string" minOccurs="0"/>
              <xs:element name="MAC" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
 </xs:element>

</xs:schema>

=== pgarman524/lenguaje-de-marcas-T4/act05/alumnado_X.xml
<?xml version="1.0" encoding="UTF-8"?>

<Alumnado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alumnado.xsd">
    <Estudiante>
        <NIF>12345678A</NIF>
        <Resultado>apto</Resultado>
        <Observaciones>Buen estudiante</Observaciones>
        <IP>192.168.1.1</IP>
    </Estudiante>
    <Estudiante>
        <NIF>23456789B</NIF>
        <Resultado>No apto</Resultado>
        <Observaciones>Mal estudiante</Observaciones>
        <MAC>00:11:22:33:44:55</MAC>
 
    </Estudiante>
</Alumnado>
