=== pgarman524/lenguaje-de-marcas-T4/act01/biblioteca/biblioteca.dtd
<!ELEMENT libros (libro*)>
<!ELEMENT libro (autor*, titulo, editorial, fechaPublicacion, ISBN)>
<!ELEMENT autor (apellido1, apellido2, nombre)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT fechaPublicacion (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>

=== pgarman524/lenguaje-de-marcas-T4/act01/biblioteca/biblioteca_D.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "biblioteca.dtd">
<libros>
<libro>

        <autor>
            <apellido1>Follet</apellido1>
            <apellido2></apellido2>
            <nombre>Ken</nombre>
        </autor>
   
    <titulo>La Armadura de la Luz</titulo>
    <editorial>Plaza RJ Janés</editorial>
    <fechaPublicacion>26/09/2023</fechaPublicacion>
    <ISBN>9788401030130</ISBN>

</libro>

<libro>

   
        <autor>
            <apellido1>García</apellido1>
            <apellido2>Márquez</apellido2>
            <nombre>Gabriel</nombre>
        </autor>

    <titulo>Cien años de soledad</titulo>
    <editorial>Debolsillo</editorial>
    <fechaPublicacion>24/01/2003</fechaPublicacion>
    <ISBN>9788497592208</ISBN>

</libro>
<libro>


        <autor>
            <apellido1>Uderzo</apellido1>
            <apellido2></apellido2>
            <nombre>Albert</nombre>
        </autor>

    <titulo>Asterix el libro Blanco</titulo>
    <editorial>Salvat</editorial>
    <fechaPublicacion>26/10/2023</fechaPublicacion>
    <ISBN>9788469640401</ISBN>

</libro>
<libro>

 
        <autor>
            <apellido1>Rooney</apellido1>
            <apellido2></apellido2>
            <nombre>Sally</nombre>
        </autor>

    <titulo>Normal People</titulo>
    <editorial>Faber and Faber</editorial>
    <fechaPublicacion>23/05/2019</fechaPublicacion>
    <ISBN>9780571334650</ISBN>

</libro>
<libro>


        <autor>
            <apellido1>Perez</apellido1>
            <apellido2>Reberte</apellido2>
            <nombre>Arturo</nombre>
        </autor>

 
    <titulo>Limpieza de Sangre</titulo>
    <editorial>Debolsillo</editorial>
    <fechaPublicacion>22/09/2016</fechaPublicacion>
    <ISBN>9788466329156</ISBN>

</libro>
<libro>


        <autor>
            <apellido1>Gratacós</apellido1>
            <apellido2></apellido2>
            <nombre>Tony</nombre>
        </autor>

    <titulo>Nadie lo sabe</titulo>
    <editorial>Destino</editorial>
    <fechaPublicacion>02/03/2022</fechaPublicacion>
    <ISBN>9788423361021</ISBN>

</libro>
<libro>

 
        <autor>
            <apellido1>Navarro</apellido1>
            <apellido2></apellido2>
            <nombre>Julia</nombre>
        </autor>

    <titulo>Dispara, yo ya estoy muerto</titulo>
    <editorial>Plaza y Janes Editores</editorial>
    <fechaPublicacion>29/08/2013</fechaPublicacion>
    <ISBN>9788401354694</ISBN>

</libro>
<libro>


        <autor>
            <apellido1>Morenos</apellido1>
            <apellido2>Ríos</apellido2>
            <nombre>Moreno</nombre>
        </autor>

    <titulo>En el camping del Gran Fogón </titulo>
    <editorial>ANTON PIÑON</editorial>
    <fechaPublicacion>14/09/2023</fechaPublicacion>
    <ISBN>9788411820219</ISBN>

</libro>
<libro>


        <autor>
            <apellido1>Brown</apellido1>
            <apellido2></apellido2>
            <nombre>Sarah</nombre>
        </autor>

    <titulo>El lenguaje secreto de los gatos</titulo>
    <editorial>geoPlaneta Ciencia</editorial>
    <fechaPublicacion>25/10/2023</fechaPublicacion>
    <ISBN>9788408277125</ISBN>

</libro>
<libro>


        <autor>
            <apellido1>Sanderson</apellido1>
            <apellido2></apellido2>
            <nombre>Brandon</nombre>
        </autor>

    <titulo>El hoombre Iluminado</titulo>
    <editorial>Nova</editorial>
    <fechaPublicacion>19/10/2023</fechaPublicacion>
    <ISBN>9788419260123</ISBN>

</libro>
<libro>


        <autor>
            <apellido1>Mesa</apellido1>
            <apellido2></apellido2>
            <nombre>Sara</nombre>
        </autor>

    <titulo>Un amor</titulo>
    <editorial>Anagrama</editorial>
    <fechaPublicacion>02/09/2020</fechaPublicacion>
    <ISBN>9788433999030</ISBN>

</libro>
<libro>


        <autor>
            <apellido1>Clear</apellido1>
            <apellido2></apellido2>
            <nombre>James</nombre>
        </autor>

    <titulo>Hábitos atómicos</titulo>
    <editorial>Diana</editorial>
    <fechaPublicacion>08/09/2020</fechaPublicacion>
    <ISBN>9788418118036</ISBN>

</libro>
</libros>
