=== pgarman524/lenguaje-de-marcas-T4/act06/lmsgi.dtd
<!ELEMENT modulos (modulo*)>
<!ELEMENT modulo (nombre, contenido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT contenido (unidad*)>
<!ELEMENT unidad (num, titulo, descripcion)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

=== pgarman524/lenguaje-de-marcas-T4/act06/lmsgi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modulos SYSTEM "lmsgi.dtd">
<modulos>
    <modulo>
        <nombre>Lenguajes de Marcas y Sistemas de Gestión de Información</nombre>
        <contenido>
            <unidad>
                <num>01</num>
                <descripcion>Cosas varias</descripcion>
            </unidad>
            <unidad>
                <num>02</num>
                <descripcion>Va de sumar y restar</descripcion>
            </unidad>
        </contenido>
    </modulo>
    <modulo>
        <nombre>Sistemas Informáticos</nombre>
        <contenido>
            <unidad>
                <num>01</num>
                <descripcion>Cosas varias</descripcion>
            </unidad>
            <unidad>
                <num>02</num>
                <descripcion>Va de sumar y restar</descripcion>
            </unidad>
        </contenido>
    </modulo>
    <modulo>
        <nombre>Bases de Datos</nombre>
        <contenido>
            <unidad>
                <num>01</num>
                <descripcion>Cosas varias</descripcion>
            </unidad>
            <unidad>
                <num>02</num>
                <descripcion>Va de sumar y restar</descripcion>
            </unidad>
        </contenido>
    </modulo>
    <modulo>
        <nombre>Programación</nombre>
        <contenido>
            <unidad>
                <num>01</num>
                <descripcion>Cosas varias</descripcion>
            </unidad>
            <unidad>
                <num>02</num>
                <descripcion>Va de sumar y restar</descripcion>
            </unidad>
        </contenido>
    </modulo>
    <modulo>
        <nombre>Entornos de Desarrollo</nombre>
        <contenido>
            <unidad>
                <num>01</num>
                <descripcion>Cosas varias</descripcion>
            </unidad>
            <unidad>
                <num>02</num>
                <descripcion>Va de sumar y restar</descripcion>
            </unidad>
        </contenido>
    </modulo>
   
    <modulo>
        <nombre>Formación y Orientación Laboral</nombre>
        <contenido>
            <unidad>
                <num>01</num>
                <descripcion>Cosas varias</descripcion>
            </unidad>
            <unidad>
                <num>02</num>
                <descripcion>Va de sumar y restar</descripcion>
            </unidad>
        </contenido>
    </modulo>
 
</modulos>
