=== pgarman524/lenguaje-de-marcas-T4/act07/editorial.dtd
<!ELEMENT editorial (descripcion, fecha, region)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT region (norte, centro, sur)>
<!ELEMENT norte (trimestres)>
<!ELEMENT centro (trimestres)>
<!ELEMENT sur (trimestres)>
<!ELEMENT trimestres (trimestre1, trimestre2, trimestre3, trimestre4)>
<!ELEMENT trimestre1 (librosVendidos)>
<!ELEMENT trimestre2 (librosVendidos)>
<!ELEMENT trimestre3 (librosVendidos)>
<!ELEMENT trimestre4 (librosVendidos)>
<!ELEMENT librosVendidos (#PCDATA)>

=== pgarman524/lenguaje-de-marcas-T4/act07/editorial_D.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE editorial SYSTEM "editorial.dtd">
<editorial>
    <descripcion>Informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    <fecha>30/12/2009</fecha>
    <region>
        
        <norte>
            <trimestres>
                <trimestre1>
                    <librosVendidos>
                        24000
                    </librosVendidos>
                </trimestre1>    
    
                <trimestre2>
                    <librosVendidos>
                        38600
                    </librosVendidos>
                </trimestre2>    
                
                <trimestre3>
                    <librosVendidos>
                        "NO_INFO"
                    </librosVendidos>
                </trimestre3> 
                
                <trimestre4>
                    <librosVendidos>
                        "NO_INFO"
                    </librosVendidos>
                </trimestre4> 
            </trimestres>
        </norte>
        <centro>
            <trimestres>
                <trimestre1>
                    <librosVendidos>
                        "NO_INFO"
                    </librosVendidos>
                </trimestre1>    
    
                <trimestre2>
                    <librosVendidos>
                        16080
                    </librosVendidos>
                </trimestre2>    
                
                <trimestre3>
                    <librosVendidos>
                        25000
                    </librosVendidos>
                </trimestre3> 
                
                <trimestre4>
                    <librosVendidos>
                        29000
                    </librosVendidos>
                </trimestre4> 
            </trimestres>
        </centro>
        <sur>
            <trimestres>
                <trimestre1>
                    <librosVendidos>
                        27000
                    </librosVendidos>
                </trimestre1>    
    
                <trimestre2>
                    <librosVendidos>
                        31400
                    </librosVendidos>
                </trimestre2>    
                
                <trimestre3>
                    <librosVendidos>
                        40100
                    </librosVendidos>
                </trimestre3> 
                
                <trimestre4>
                    <librosVendidos>
                        30000
                    </librosVendidos>
                </trimestre4> 
            </trimestres>
        </sur>
    </region>

</editorial>
