=== pgarman524/lenguaje-de-marcas-T4/act05/Mejoras/libreria.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:element name="Libreria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ISBN" type="xs:string"/>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="autor" type="xs:string"/>
              <xs:element name="disponible" type="xs:string"/>
              <xs:element name="notas" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
 </xs:element>

</xs:schema>

=== pgarman524/lenguaje-de-marcas-T4/act05/Mejoras/libreria _X.xml
<?xml version="1.0" encoding="UTF-8"?>

<Libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="libreria.xsd">
    <libro>
        <ISBN>1234567890</ISBN>
        <titulo>EL Lazarillo de Tormes</titulo>
        <autor>none</autor>
        <disponible>no</disponible>
        <notas>null</notas>
    </libro>
    <libro>
        <ISBN>0987654321</ISBN>
        <titulo>Harry Potter</titulo>
        <autor>JK. Rowlin</autor>
        <disponible>s√≠</disponible>
        <notas>Ta' perfe</notas>
    </libro>
</Libreria>
